<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Lista de Empleados</title>
        <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
    </head>
    <body>
        <!-- <h1>Slim</h1>
        <div>a microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?> -->

        <div class="container">
            
            <div class="row text-center">
                <h1 class="title">Lista de Empleados</h1>
            </div>

            <br />
            <div class="row">
                <form class="form-inline" id="search_email" method="post" action="../all_list">
                  <input type="submit" class="btn btn-primary pull-right" value="Ver lista completa" />
                </form>
            </div>
            <br />
            <div class="row">
                <div class="col-md-12">
                    <form action="" method="POST" role="form">
                        <legend>Detalle del empleado</legend>
                    
                        <div class="form-group">
                            <label for="">Name</label>
                            <input type="text" class="form-control" id="" placeholder="Input field" value="<?= $employees[0]['name'] ?>" disabled="disabled" />
                        </div>
                        <div class="form-group">
                            <label for="">Email</label>
                            <input type="text" class="form-control" id="" placeholder="Input field" value="<?= $employees[0]['email'] ?>" disabled="disabled" />
                        </div>
                        <div class="form-group">
                            <label for="">Phone</label>
                            <input type="text" class="form-control" id="" placeholder="Input field" value="<?= $employees[0]['phone'] ?>" disabled="disabled" />
                        </div>
                        <div class="form-group">
                            <label for="">Address</label>
                            <input type="text" class="form-control" id="" placeholder="Input field" value="<?= $employees[0]['address'] ?>" disabled="disabled" />
                        </div>
                        <div class="form-group">
                            <label for="">Position</label>
                            <input type="text" class="form-control" id="" placeholder="Input field" value="<?= $employees[0]['position'] ?>" disabled="disabled" />
                        </div>
                        <div class="form-group">
                            <label for="">Salary</label>
                            <input type="text" class="form-control" id="" placeholder="Input field" value="<?= $employees[0]['salary'] ?>" disabled="disabled" />
                        </div>     
                        <div class="form-group">
                            <label for="">Skills</label>
                            <br />
                            <ul>
                            <?php
                                for($i=0; $i<count($employees[0]['skills']); $i++)
                                {
                            ?>
                                    <li><?= $employees[0]['skills'][$i]['skill'] ?></li>
                            <?php
                                }
                            ?>
                            </ul>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </body>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>
